Update .NET_Build.yml

diff --git a/.github/workflows/.NET_Build.yml b/.github/workflows/.NET_Build.yml
--- a/.github/workflows/.NET_Build.yml
+++ b/.github/workflows/.NET_Build.yml
@@ -4,6 +4,33 @@ on:
   workflow_dispatch:
   
 jobs:
+
+  Build_Parameters:
+      runs-on: ubuntu-latest      
+      steps:
+      
+        - name: CheckOut SourceCode
+          uses: actions/checkout@v3
+
+        - name: Set Release Version
+          id: versionid
+          run: | 
+                 echo "Set Release Version"
+                 exit 1
+
+        - name: Cancel Workflow     
+          if: failure()
+          run: |
+              echo "::error::Cancelling workflow due to one of the jobs failing."
+              curl \
+              -X POST \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer ${{ secrets.SKIPTOKEN }}"\
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              https://api.github.com/repos/shiyamsundark/sample-dotnet-app/actions/runs/${{ github.run_id }}/cancel
+#          env:
+#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
   Build:
     runs-on: windows-latest
     steps:
@@ -16,32 +43,33 @@ jobs:
         dotnet-version: 5.0.x
         
     - name: Restore dependencies
-      run: dotnet restore
+      run: echo "dotnet restore"
       
     - name: Build
-      run: dotnet build --no-restore
-      
-    - name: Package creation
       run: |
-           mkdir sample_test
-           mv ./bin/Debug/netcoreapp2.2/* ./sample_test
+           echo "dotnet build --no-restore"
+      
+#     - name: Package creation
+#       run: |
+#            mkdir sample_test
+#            mv ./bin/Debug/netcoreapp2.2/* ./sample_test
                     
-    - name: Upload a Build Artfifact
-      uses: actions/upload-artifact@v2
-      with:
-        name: sample_test
-        path: ./sample_test
-        retention-days: 1
+#     - name: Upload a Build Artfifact
+#       uses: actions/upload-artifact@v2
+#       with:
+#         name: sample_test
+#         path: ./sample_test
+#         retention-days: 1
       
   sonar:
      name: Sonar Analysis
-     needs: Build
+     needs: [Build,Build_Parameters]
      uses: ./.github/workflows/sonar.yml
      
   Upload_Artifact_GitHub_Release:
          
        runs-on: ubuntu-latest
-       needs: [Build,sonar]
+       needs: [Build,sonar,Build_Parameters]
        permissions:
           contents: write
           packages: write
@@ -50,34 +78,34 @@ jobs:
        
          - uses: actions/checkout@v3   
          
-         - run: mkdir test
+#          - run: mkdir test
          
-         - name: Dowload a Build Artfifact
-           uses: actions/download-artifact@v2
-           with:
-             name: sample_test
-             path: ./test
+#          - name: Dowload a Build Artfifact
+#            uses: actions/download-artifact@v2
+#            with:
+#              name: sample_test
+#              path: ./test
              
-         - run : 7z a test.zip ./test
+#          - run : 7z a test.zip ./test
          
-         - name: Create Github Release
-           id: create_release
-           uses: actions/create-release@v1
-           env:
-             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
-           with:
-             tag_name: test_sample_v1
-             release_name: sample-test
+#          - name: Create Github Release
+#            id: create_release
+#            uses: actions/create-release@v1
+#            env:
+#              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
+#            with:
+#              tag_name: test_sample_v1
+#              release_name: sample-test
              
-         - name: Upload Artifacts to Github Release
-           uses: actions/upload-release-asset@v1
-           env:
-             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
-           with:
-              upload_url: ${{ steps.create_release.outputs.upload_url }}
-              asset_path: ./test.zip
-              asset_name: sample_test.zip
-              asset_content_type: application/zip
+#          - name: Upload Artifacts to Github Release
+#            uses: actions/upload-release-asset@v1
+#            env:
+#              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
+#            with:
+#               upload_url: ${{ steps.create_release.outputs.upload_url }}
+#               asset_path: ./test.zip
+#               asset_name: sample_test.zip
+#               asset_content_type: application/zip
      
 #   upload:
 #     runs-on: windows-latest
